version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
  client-app:
    build: ./client
    environment:
      - VITE_PROXY_HOST=http://server-app:8080
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    ports:
      - 5173:5173
  server-app:
    build: ./server
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017
    volumes:
      - ./server/src:/server/src
    ports:
      - 8080:8080
