version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
  client-app:
    build: ./gomoku-react
    environment:
      - VITE_PROXY_HOST=http://server-app:8080
    volumes:
      - ./gomoku-react/src:/gomoku-react/src
      - ./gomoku-react/public:/gomoku-react/public
    ports:
      - 5173:5173
  server-app:
    build: ./gomoku-service
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017
    volumes:
      - ./gomoku-service/src:/gomoku-service/src
    ports:
      - 8080:8080